u21512338_HW03/Models/FileModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace u21512338_HW03.Models
{
    public class FileModel
    {
        //filename
        [Display(Name = "File Name")]
        public string FileName { get; set; }

        //chosen files
        [Required(ErrorMessage = "Please select file.")]
        [Display(Name = "Browse File")]
        public HttpPostedFileBase[] Files { get; set; }

        //radio button type
        public string Type { get; set; }

        //image path
        public string Image { get; set; }

        //video path
        public string Vid { get; set; }

    }
}

u21512338_HW03/Controllers/DocDownloadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using u21512338_HW03.Models;

namespace u21512338_HW03.Controllers
{
    public class DocDownloadController : Controller
    {
        // GET: DocDownload
        public ActionResult Index()
        {
            //Fetch all files in the Folder (Directory).

            string[] filePaths = Directory.GetFiles(Server.MapPath("~/Media/Documents/"));

            //Copy File names to Model collection.
            //The return below returns to the list here.

            List<FileModel> files = new List<FileModel>();

            foreach (string filePath in filePaths)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filePath) });
            }
            return View(files);
        }

        public FileResult DownloadFile(string fileName) 
        {
            //File Path.
            string path = Server.MapPath("~/Media/Documents/") + fileName;

            //Read the File data into Byte Array.
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            //Send the File to Download.
            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {
            //The file is deleted based on the identified file path.

            string path = Server.MapPath("~/Media/Documents/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }
    }
}

u21512338_HW03/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using u21512338_HW03.Models;

namespace u21512338_HW03.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult About()
        {
            return View();
        }

        // GET: FileUpload
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase files, FileModel model)
        {
            // Verify that the user selected a file
            // Not null and has a length
            if (files != null && files.ContentLength > 0)
            {
                // extract only the filename
                var fileName = Path.GetFileName(files.FileName);
                //extract radio button type
                var selectedType = model.Type;

                if (selectedType == "Document") //document radio button
                {
                    var path = Path.Combine(Server.MapPath("~/Media/Documents/"), fileName);

                    // The chosen default path for saving

                    files.SaveAs(path);
                }
                else if (selectedType == "Image") //image radio button
                {
                    var path = Path.Combine(Server.MapPath("~/Media/Images/"), fileName);

                    // The chosen default path for saving

                    files.SaveAs(path);
                }
                else if (selectedType == "Video") //video radio button
                {
                    var path = Path.Combine(Server.MapPath("~/Media/Videos/"), fileName);

                    // The chosen default path for saving

                    files.SaveAs(path);
                }
            }

            // redirect back to the index action to show the form once again
            return RedirectToAction("Index");
        }
    }
}

u21512338_HW03/Controllers/ImageDownloadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using u21512338_HW03.Models;

namespace u21512338_HW03.Controllers
{
    public class ImageDownloadController : Controller
    {
        // GET: ImageDownload
        public ActionResult Index()
        {
            //Fetch all files in the Folder (Directory).
            string[] filePaths = Directory.GetFiles(Server.MapPath("~/Media/Images/"));

            //Copy File names to Model collection.
            //The return below returns to the list here.

            List<FileModel> images = new List<FileModel>();

            foreach (string filePath in filePaths)
            {
                images.Add(new FileModel { FileName = Path.GetFileName(filePath), Image = "~/Media/Images/" + Path.GetFileName(filePath) });
            }
            return View(images);
        }

        public FileResult DownloadFile(string fileName) 
        {
            //Build the File Path.
            string path = Server.MapPath("~/Media/Images/") + fileName;

            //Read the File data into Byte Array.
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            //Send the File to Download.
            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {
            //Delete requires reading the files and then the allocation of a file path.
            string path = Server.MapPath("~/Media/Images/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }
    }
}

u21512338_HW03/Controllers/VideoDownloadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using u21512338_HW03.Models;

namespace u21512338_HW03.Controllers
{
    public class VideoDownloadController : Controller
    {
        // GET: VideoDownload
        public ActionResult Index()
        {
            //Fetch all files in the Folder (Directory).
            string[] filePaths = Directory.GetFiles(Server.MapPath("~/Media/Videos/"));

            //Copy File names to Model collection.
            //The return below returns to the list here.

            List<FileModel> videos = new List<FileModel>();

            foreach (string filePath in filePaths)
            {
                videos.Add(new FileModel { FileName = Path.GetFileName(filePath), Vid = "~/Media/Videos/" + Path.GetFileName(filePath) });
            }
            return View(videos);
        }

        public FileResult DownloadFile(string fileName) 
        {
            //Build the File Path.
            string path = Server.MapPath("~/Media/Videos/") + fileName;

            //Read the File data into Byte Array.
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            //Send the File to Download.
            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {
            //Delete requires reading the files and then the allocation of a file path.
            string path = Server.MapPath("~/Media/Videos/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }
    }
}

u21512338_HW03/Views/DocDownload/Index.cshtml
@using u21512338_HW03.Models
@model List<FileModel>

@{
    ViewBag.Title = "Index";
}

<h2>Documents of any file type</h2>
<h4>..."Media/Documents/" folder</h4>

<head>
    <style type="text/css">
        .tb-style {
            color: #FFFFFF;
        }

        .th {
            text-align: center;
            vertical-align: middle;
        }
    </style>
</head>

<div style="height: auto; overflow: auto; background-color: lightgray">
    <div class="well-sm">
        <table class="table table-condensed table-hover">
            <thead style="position: sticky;top: 0">
                <tr bgcolor="#222222" class="tb-style">
                    <th class="col-lg-8">File Name</th>
                    <th class="th, col-lg-2">DOWNLOAD</th>
                    <th class="th, col-lg-2">DELETE</th>
                </tr>
            </thead>
            @*iterate through files in model and display relevant documents*@
            @foreach (FileModel file in Model)
            {
                <tr>
                    <td>@file.FileName</td>
                    <td>
                        <button class="btn btn-success">
                            @Html.ActionLink("Download", "DownloadFile",
                            new { fileName = file.FileName },
                            new { @style = "color:white;" }) @*white text*@
                        </button>
                    </td>
                    <td>
                        <button class="btn btn-danger">
                            @Html.ActionLink("DELETE", "DeleteFile",
                            new { fileName = file.FileName },
                            new { @style = "color:white;" }) @*white text*@
                        </button>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

u21512338_HW03/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<h2>About Me</h2>
<h5>u21512338</h5>

<div style="height: auto; overflow: auto; background-color: lightgray">
    <div class="well-sm">
        <div class="col-lg-6">
            <div>
                <h3>Bio</h3>
            </div>
            <div>
                <p>
                    My name is Nikita Jade Haskins and I am a student at the University of Pretoria. I am currently studying BIT Information Systems and
                    am pursuing the Information Science stream. My current achievements include becoming a Golden Key member at the beginning of this year (2022).
                    <br /><br />
                    I grew up in Pietermaritzburg, where I attended Pietermaritzburg Girls High School. I did not enjoy sports and as such focused on academics
                    for the majority of my high school career. While some aspects were enjoyable, as a whole I did not enjoy school and am much happier in a
                    university environment. I now stay at a university residence.
                    <br /><br />
                    At home I have three dogs, four cats, and three guinea pigs. I very much love my animals and look forward to seeing them every holiday.
                </p>
            </div>
        </div>
        <div class="col-lg-6">
            <div>
                <h3>Nikita Haskins</h3>
            </div>
            <div>
                <img src="@Url.Content("~/About_Image/NikitaHaskins.jpg")" alt="About Me Image" style="height : 250px; width : 300px;">
            </div>
        </div>
    </div>
</div>

u21512338_HW03/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>myMedia</h2>
<h4>Select File to be uploaded</h4>

<div style="height: auto; overflow: auto; background-color: lightgray">
    <div class="well-sm">
        <div class="col-lg-8">
            <div>
                <h3>Description</h3>
            </div>
            <div>
                <p>This system allows a user to upload any document type to the relevant headings. Images should only be in image format, likewise videos should be in video format. Documents can be of any type. The best part is - everything you upload remains in the system files and ready to use next time! Any file uploaded can be downloaded again or deleted permanently. There is an about me page that gives a brief overview of the system builder. Take your time to explore and enjoy our system. Thank you!</p>
            </div>
        </div>

        <div class="col-lg-4">
            <div>
                <h3>Options Selection</h3>
            </div>
            <div class="well-sm">
                <div class="form-horizontal">
                    @using (Html.BeginForm("Index", "Home", FormMethod.Post, new { enctype = "multipart/form-data" })) 
                        // an encoding type that allows files to be sent through a POST.
                    {
                        <div>
                            <input type="radio" value="Document" id="Type" name="Type" checked="checked" /> Document<br />
                            <input type="radio" value="Image" id="Type" name="Type" /> Image<br />
                            <input type="radio" value="Video" id="Type" name="Type" /> Video<br />
                        </div>
                        <br />
                        <div><input type="file" name="files" /></div>
                        <br />
                        <div><input type="submit" value="Upload" /></div>
                    }
                </div>
                <br />
            </div>
        </div>
    </div>
</div>

u21512338_HW03/Views/ImageDownload/Index.cshtml
@using u21512338_HW03.Models
@model List<FileModel>

@{
    ViewBag.Title = "Index";
}

<h2>Images Files</h2>
<h4>..."Media/Images/" folder</h4>

<head>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.mousewheel-3.0.6.pack.js"></script>
    <script src="~/Scripts/jquery.fancybox.js"></script>
    <link rel="stylesheet" type="text/css" href="~/Content/jquery.fancybox.css" media="screen">
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.fancybox.pack.js"></script>
</head>

<div style="height: auto; overflow: auto; background-color: lightgray">
    <div class="well-sm">
        @*iterate through files in model and display relevant images*@
        @foreach (FileModel images in Model)
        {
            <div class="col-lg-4 col-md-6"> @*3 images per row on large screen*@
                <br />
                <div>
                    <a href="@Url.Content(images.Image)" class="fancybox-image"> @*fancybox*@
                        <img src="@Url.Content(images.Image)" alt="uploadImage" style="height:170px;width:270px;" />
                    </a>
                </div>
                <div>@images.FileName</div>
                <div>
                    <button class="btn btn-success">
                        @Html.ActionLink("Download", "DownloadFile",
                         new { fileName = images.FileName },
                         new { @style = "color:white;" })
                    </button>
                    <button class="btn btn-danger">
                        @Html.ActionLink("DELETE", "DeleteFile",
                         new { fileName = images.FileName },
                         new { @style = "color:white;" })
                    </button>

                </div>
                <br />
            </div>

        }

    </div>
</div>


<script>
    /*fancybox script*/
    $(document).ready(function ($) {
        $(".fancybox-image").fancybox();
    });
</script>

u21512338_HW03/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Files", "Index", "DocDownload")</li>
                    <li>@Html.ActionLink("Images", "Index", "ImageDownload")</li>
                    <li>@Html.ActionLink("Videos", "Index", "VideoDownload")</li>
                    <li>@Html.ActionLink("About Me", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

u21512338_HW03/Views/VideoDownload/Index.cshtml
@using u21512338_HW03.Models
@model List<FileModel>

@{
    ViewBag.Title = "Index";
}

<h2>Video Files</h2>
<h4>..."Media/Video/" folder</h4>

<head>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.mousewheel-3.0.6.pack.js"></script>
    <script src="~/Scripts/jquery.fancybox.js"></script>
    <link rel="stylesheet" type="text/css" href="~/Content/jquery.fancybox.css" media="screen">
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.fancybox.pack.js"></script>
</head>

<div style="height: auto; overflow: auto; background-color: lightgray">
    <div class="well-sm">
        @*iterate through files in model and display relevant videos*@
        @foreach (FileModel videos in Model)
        {
            <div class="col-lg-4 col-md-6"> @*3 videos per row on large screen*@
                <br />
                <div>
                    <a class="fancybox" href="@Url.Content(videos.Vid)"> @*fancybox*@
                        <video width="270" height="170" controls>
                            <source src="@Url.Content(videos.Vid)" type="video/mp4">
                        </video>
                    </a>
                </div>
                <div>@videos.FileName</div>
                <div>
                    <button class="btn btn-success">
                        @Html.ActionLink("Download", "DownloadFile",
                        new { fileName = videos.FileName },
                        new { @style = "color:white;" })
                    </button>
                    <button class="btn btn-danger">
                        @Html.ActionLink("DELETE", "DeleteFile",
                        new { fileName = videos.FileName },
                        new { @style = "color:white;" })
                    </button>

                </div>
                <br />
            </div>

        }

    </div>
</div>

<script>
    /*fancybox script*/
    $(document).ready(function ($) {
        $(".fancybox").fancybox({
            width: 800,
            height: 600,
            type: 'iframe'
        });
    });
</script>